name: jnap
description: A library for handling JNAP actions and services.
version: 1.0.6
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0
  http: ^1.2.2
  equatable: ^2.0.7
  async: ^2.13.0
  logger: ^2.5.0
  encrypt: ^5.0.3


dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.0
  lints: ^3.0.0
  mockito: ^5.4.4
