// Mocks generated by Mockito 5.4.6 from annotations
// in jnap/test/src/side_effects_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jnap/jnap.dart' as _i2;
import 'package:jnap/src/utilties/http/http_client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJNAPSuccess_0 extends _i1.SmartFake implements _i2.JNAPSuccess {
  _FakeJNAPSuccess_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJNAPTransactionSuccessWrap_1 extends _i1.SmartFake
    implements _i2.JNAPTransactionSuccessWrap {
  _FakeJNAPTransactionSuccessWrap_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Jnap].
///
/// See the documentation for Mockito's code generation for more information.
class MockJnap extends _i1.Mock implements _i2.Jnap {
  MockJnap() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.JNAPResult> scheduled({
    required _i2.JNAPAction? action,
    Map<String, dynamic>? data = const {},
    Map<String, String>? headers = const {},
    _i2.JNAPConfigOverrides? overrides,
    int? retryDelayInMilliSec = 5000,
    int? maxRetry = 10,
    int? firstDelayInMilliSec = 3000,
    bool Function(_i2.JNAPResult)? condition,
    int? requestTimeoutOverride,
    bool? auth = false,
    void Function(
      _i2.JNAPResult?,
      Object?,
    )? onComplete,
    _i4.HttpClient? httpClient,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduled,
          [],
          {
            #action: action,
            #data: data,
            #headers: headers,
            #overrides: overrides,
            #retryDelayInMilliSec: retryDelayInMilliSec,
            #maxRetry: maxRetry,
            #firstDelayInMilliSec: firstDelayInMilliSec,
            #condition: condition,
            #requestTimeoutOverride: requestTimeoutOverride,
            #auth: auth,
            #onComplete: onComplete,
            #httpClient: httpClient,
          },
        ),
        returnValue: _i3.Stream<_i2.JNAPResult>.empty(),
      ) as _i3.Stream<_i2.JNAPResult>);

  @override
  _i3.Future<_i2.JNAPSuccess> send({
    required _i2.JNAPAction? action,
    Map<String, dynamic>? data = const {},
    Map<String, String>? headers = const {},
    _i2.JNAPConfigOverrides? overrides,
    _i2.JNAPSideEffectOverrides? sideEffectOverrides,
    _i4.HttpClient? httpClient,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [],
          {
            #action: action,
            #data: data,
            #headers: headers,
            #overrides: overrides,
            #sideEffectOverrides: sideEffectOverrides,
            #httpClient: httpClient,
          },
        ),
        returnValue: _i3.Future<_i2.JNAPSuccess>.value(_FakeJNAPSuccess_0(
          this,
          Invocation.method(
            #send,
            [],
            {
              #action: action,
              #data: data,
              #headers: headers,
              #overrides: overrides,
              #sideEffectOverrides: sideEffectOverrides,
              #httpClient: httpClient,
            },
          ),
        )),
      ) as _i3.Future<_i2.JNAPSuccess>);

  @override
  _i3.Future<_i2.JNAPTransactionSuccessWrap> transaction({
    required _i2.JNAPTransactionBuilder? transactionBuilder,
    Map<String, String>? headers = const {},
    _i2.JNAPConfigOverrides? overrides,
    _i2.JNAPSideEffectOverrides? sideEffectOverrides,
    _i4.HttpClient? httpClient,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [],
          {
            #transactionBuilder: transactionBuilder,
            #headers: headers,
            #overrides: overrides,
            #sideEffectOverrides: sideEffectOverrides,
            #httpClient: httpClient,
          },
        ),
        returnValue: _i3.Future<_i2.JNAPTransactionSuccessWrap>.value(
            _FakeJNAPTransactionSuccessWrap_1(
          this,
          Invocation.method(
            #transaction,
            [],
            {
              #transactionBuilder: transactionBuilder,
              #headers: headers,
              #overrides: overrides,
              #sideEffectOverrides: sideEffectOverrides,
              #httpClient: httpClient,
            },
          ),
        )),
      ) as _i3.Future<_i2.JNAPTransactionSuccessWrap>);
}
